added testing

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,3 +19,17 @@ jobs:
           github token: ${{ secrets.GITHUB_TOKEN }}
       - name: Verify Kubectl Test Plugin
         run: kubectl test --help
+      - name: Test
+        run: |
+          kubectl apply -f tests/job-success.yml
+          sleep 10
+          kubectl test check
+
+          kubectl apply -f tests/job-failure.yml
+          sleep 10
+          if kubectl test check ; then
+              echo "Second job should fail"
+              exit 1
+          else
+              exit 0
+          fi
